Rails.application.routes.draw do
  get 'home/index'
  get 'home/login' , to: 'home#login'
  get 'home/signup' , to: 'home#signup'
  get 'home/index' , to: 'home#index'  
  get 'home/places', to: 'home#places' 
  get 'home/first', to: 'home#first' 
  get 'home/second', to: 'home#second'
  get 'home/third', to: 'home#third'
  get 'home/fourth', to: 'home#fourth'
  get 'home/fifth', to: 'home#fifth'
  get 'home/sixth', to: 'home#sixth'
  post 'home/like', to: 'home#like'
  post 'home/save', to: 'home#save' 
  get 'home/save', to: 'home#save'  
  post 'home/save', to: 'home#save'
  get 'home/logout', to: 'home#logout' 
  root 'home#index'
end
